filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/messages
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after

output.logstash:
  hosts: ["188.166.43.135:5000"]

